$(document).ready(function(){
$(".line-item").mouseenter(function(){
alert("dsfdsf");
x=$(this).find(".num").val()
y=$(this).find('#price').html();
$(this).find(".minus").click(function(){
if(x!=1)
{
$(this).parents("div.line-item").find(".num").val(x-1);
$(this).parents("div.line-item").find("#price1").html((x-1)*y);
}
$(this).find(".plus").click(function(){
$(this).parents("div.line-item").find(".num").val(x-(-1));
$(this).parents("div.line-item").find("#price1").html((x-(-1))*y);
}
});
});
});
